# TCL File Generated by Component Editor 15.1
# Fri Dec 16 23:27:12 CET 2016
# DO NOT MODIFY


# 
# VGA_module "VGA_module" v1.2
#  2016.12.16.23:27:12
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module VGA_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME VGA_module
set_module_property VERSION 1.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Display
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME VGA_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file VGA_Module.vhd VHDL PATH ../hdl/VGA_Module.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink pixel_clk_25MHz clk Input 1


# 
# connection point vga_signal
# 
add_interface vga_signal conduit end
set_interface_property vga_signal associatedClock clock_sink
set_interface_property vga_signal associatedReset reset_sink
set_interface_property vga_signal ENABLED true
set_interface_property vga_signal EXPORT_OF ""
set_interface_property vga_signal PORT_NAME_MAP ""
set_interface_property vga_signal CMSIS_SVD_VARIABLES ""
set_interface_property vga_signal SVD_ADDRESS_GROUP ""

add_interface_port vga_signal vga_b b Output 8
add_interface_port vga_signal vga_clk clk Output 1
add_interface_port vga_signal vga_g g Output 8
add_interface_port vga_signal vga_hsync hsync Output 1
add_interface_port vga_signal vga_r r Output 8
add_interface_port vga_signal vga_vsync vsync Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point as
# 
add_interface as avalon end
set_interface_property as addressUnits WORDS
set_interface_property as associatedClock clock_sink
set_interface_property as associatedReset reset_sink
set_interface_property as bitsPerSymbol 8
set_interface_property as burstOnBurstBoundariesOnly false
set_interface_property as burstcountUnits WORDS
set_interface_property as explicitAddressSpan 0
set_interface_property as holdTime 0
set_interface_property as linewrapBursts false
set_interface_property as maximumPendingReadTransactions 0
set_interface_property as maximumPendingWriteTransactions 0
set_interface_property as readLatency 0
set_interface_property as readWaitTime 1
set_interface_property as setupTime 0
set_interface_property as timingUnits Cycles
set_interface_property as writeWaitTime 0
set_interface_property as ENABLED true
set_interface_property as EXPORT_OF ""
set_interface_property as PORT_NAME_MAP ""
set_interface_property as CMSIS_SVD_VARIABLES ""
set_interface_property as SVD_ADDRESS_GROUP ""

add_interface_port as as_write write Input 1
add_interface_port as as_addr address Input 3
add_interface_port as as_wrdata writedata Input 32
set_interface_assignment as embeddedsw.configuration.isFlash 0
set_interface_assignment as embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink_1
# 
add_interface clock_sink_1 clock end
set_interface_property clock_sink_1 clockRate 0
set_interface_property clock_sink_1 ENABLED true
set_interface_property clock_sink_1 EXPORT_OF ""
set_interface_property clock_sink_1 PORT_NAME_MAP ""
set_interface_property clock_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port clock_sink_1 system_clk clk Input 1


# 
# connection point avalon_streaming_sink
# 
add_interface avalon_streaming_sink avalon_streaming end
set_interface_property avalon_streaming_sink associatedClock clock_sink
set_interface_property avalon_streaming_sink associatedReset reset_sink
set_interface_property avalon_streaming_sink dataBitsPerSymbol 8
set_interface_property avalon_streaming_sink errorDescriptor ""
set_interface_property avalon_streaming_sink firstSymbolInHighOrderBits true
set_interface_property avalon_streaming_sink maxChannel 0
set_interface_property avalon_streaming_sink readyLatency 0
set_interface_property avalon_streaming_sink ENABLED true
set_interface_property avalon_streaming_sink EXPORT_OF ""
set_interface_property avalon_streaming_sink PORT_NAME_MAP ""
set_interface_property avalon_streaming_sink CMSIS_SVD_VARIABLES ""
set_interface_property avalon_streaming_sink SVD_ADDRESS_GROUP ""

add_interface_port avalon_streaming_sink ss_data data Input 24
add_interface_port avalon_streaming_sink ss_ready ready Output 1
add_interface_port avalon_streaming_sink ss_valid valid Input 1


# 
# connection point v_irq
# 
add_interface v_irq interrupt end
set_interface_property v_irq associatedAddressablePoint ""
set_interface_property v_irq associatedClock clock_sink
set_interface_property v_irq associatedReset reset_sink
set_interface_property v_irq bridgedReceiverOffset ""
set_interface_property v_irq bridgesToReceiver ""
set_interface_property v_irq ENABLED true
set_interface_property v_irq EXPORT_OF ""
set_interface_property v_irq PORT_NAME_MAP ""
set_interface_property v_irq CMSIS_SVD_VARIABLES ""
set_interface_property v_irq SVD_ADDRESS_GROUP ""

add_interface_port v_irq vga_v_irq irq Output 1


# 
# connection point h_irq
# 
add_interface h_irq interrupt end
set_interface_property h_irq associatedAddressablePoint ""
set_interface_property h_irq associatedClock clock_sink
set_interface_property h_irq bridgedReceiverOffset ""
set_interface_property h_irq bridgesToReceiver ""
set_interface_property h_irq ENABLED true
set_interface_property h_irq EXPORT_OF ""
set_interface_property h_irq PORT_NAME_MAP ""
set_interface_property h_irq CMSIS_SVD_VARIABLES ""
set_interface_property h_irq SVD_ADDRESS_GROUP ""

add_interface_port h_irq vga_h_irq irq Output 1

