# TCL File Generated by Component Editor 15.1
# Wed Dec 14 20:56:47 CET 2016
# DO NOT MODIFY


# 
# VGA_module "VGA_module" v1.0
#  2016.12.14.20:56:47
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module VGA_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME VGA_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Display
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME VGA_module
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_module
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file VGA_Module.vhd VHDL PATH ../hdl/VGA_Module.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink pixel_clk_25MHz clk Input 1


# 
# connection point vga_signal
# 
add_interface vga_signal conduit end
set_interface_property vga_signal associatedClock clock_sink
set_interface_property vga_signal associatedReset reset_sink
set_interface_property vga_signal ENABLED true
set_interface_property vga_signal EXPORT_OF ""
set_interface_property vga_signal PORT_NAME_MAP ""
set_interface_property vga_signal CMSIS_SVD_VARIABLES ""
set_interface_property vga_signal SVD_ADDRESS_GROUP ""

add_interface_port vga_signal vga_b b Output 8
add_interface_port vga_signal vga_clk clk Output 1
add_interface_port vga_signal vga_g g Output 8
add_interface_port vga_signal vga_hsync hsync Output 1
add_interface_port vga_signal vga_r r Output 8
add_interface_port vga_signal vga_vsync vsync Output 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock_sink
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender vga_irq irq Output 1

